name: pubsub-facades
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - python-dateutil
  - pip:
    - python-qpid_proton
    - git+https://git@github.com/eurocontrol-swim/swim-qpid-proton.git
    - git+https://git@github.com/eurocontrol-swim/rest-client.git
    - git+https://git@github.com/eurocontrol-swim/subscription-manager-client.git
    - git+https://git@github.com/eurocontrol-swim/geofencing-service-client.git
